/******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Mazen Hekal
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
		||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
		||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
#error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
		||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
		||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
#error "The SW version of PBcfg.c does not match the expected version"
#endif



const Port_ConfigType Port_Configuration = {
		PORTA,PIN0,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PA0*/
		PORTA,PIN1,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PA1*/
		PORTA,PIN2,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PA2*/
		PORTA,PIN3,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PA3*/
		PORTA,PIN4,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PA4*/
		PORTA,PIN5,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PA5*/
		PORTA,PIN6,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PA6*/
		PORTA,PIN7,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PA7*/
		PORTB,PIN0,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PB0*/
		PORTB,PIN1,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PB1*/
		PORTB,PIN2,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PB2*/
		PORTB,PIN3,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PB3*/
		PORTB,PIN4,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PB4*/
		PORTB,PIN5,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PB5*/
		PORTB,PIN6,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PB6*/
		PORTB,PIN7,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PB7*/
		PORTC,PIN4,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PC4*/
		PORTC,PIN5,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PC5*/
		PORTC,PIN6,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PC6*/
		PORTC,PIN7,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PC7*/
		PORTD,PIN0,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PD0*/
		PORTD,PIN1,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PD1*/
		PORTD,PIN2,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PD2*/
		PORTD,PIN3,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PD3*/
		PORTD,PIN4,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PD4*/
		PORTD,PIN5,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PD5*/
		PORTD,PIN6,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PD6*/
		PORTD,PIN7,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PD7*/
		PORTE,PIN0,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PE0*/
		PORTE,PIN1,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PE1*/
		PORTE,PIN2,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PE2*/
		PORTE,PIN3,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PE3*/
		PORTE,PIN4,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PE4*/
		PORTE,PIN5,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,   /*PE5*/
		PORTF,PIN0,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE,	/*PF0*/
		PORTF,PIN1,PORT_PIN_OUT,PORT_PIN_OFF,STD_LOW,PORT_MODE_DIO,TRUE,TRUE,		/*PF1*/
		PORTF,PIN2,PORT_PIN_OUT,PORT_PIN_OFF,STD_LOW,PORT_MODE_DIO,TRUE,TRUE,		/*PF2*/
		PORTF,PIN3,PORT_PIN_OUT,PORT_PIN_OFF,STD_LOW,PORT_MODE_DIO,TRUE,TRUE,		/*PF3*/
		PORTF,PIN4,PORT_PIN_IN,PORT_PIN_PULL_UP,STD_HIGH,PORT_MODE_DIO,TRUE,TRUE	/*PF4*/
};
